export const IMAGES={
    GET_IMAGES:'GET_IMAGES',
    PAGINATE_IMAGES:'PAGINATE_IMAGES',
    SET_SELECTED_IMAGE:'SET_SELECTED_IMAGE'
};
export const CATEGORY={
    GET_CATEGORY:'GET_CATEGORY',
    SET_SELECTED_CATEGORY:'SET_SELECTED_CATEGORY'
}
export const FILTERS ={
    CHANGE_FILTERS:'CHANGE_FILTERS'
}